version: '3.8'

services:
    frontend:
        build: ./frontend
        ports:
            - '80:80'
        depends_on:
            - backend
        env_file:
            - ./.env # 指定环境文件
        environment:
            - NODE_ENV=production
        networks:
            - yolopest-network

    backend:
        build: ./backend
        ports:
            - '8000:8000'
        env_file:
            - ./.env # 指定环境文件
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            # 如果需要持久化模型文件
            - ./model_weights:/app/model_weights # 模型文件映射
        networks:
            - yolopest-network

networks:
    yolopest-network:
        driver: bridge
